services:
  php:
    build: ./docker/php
    container_name: app-php
    volumes:
      - ./:/var/www/html:rw,cached
    environment:
      PHP_IDE_CONFIG: "serverName=app"
      SYMFONY_ENV: dev
    depends_on:
      db:
        condition: service_healthy
      mongo:
        condition: service_healthy

  nginx:
    image: nginx:1.27-alpine
    container_name: app-nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  db:
    image: postgres:16-alpine
    container_name: app-postgres
    environment:
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U symfony -d app -h 127.0.0.1 -p 5432"]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 10s

  adminer:
    image: adminer:4
    container_name: app-adminer
    ports:
      - "8081:8080"
    environment:
      # permet de pré-sélectionner Postgres dans l'UI (facultatif)
      ADMINER_DEFAULT_SERVER: db
    depends_on:
      - db

  mongo:
    image: mongo:7
    container_name: app-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: app
    volumes:
      - mongodata:/data/db
      - ./docker/mongo/init.js:/docker-entrypoint-initdb.d/init.js:ro
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet -u root -p root --eval 'db.runCommand({ ping: 1 })' || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 10s

  mongo-express:
    image: mongo-express:1.0.2
    container_name: app-mongo-express
    ports:
      - "8082:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: "mongodb://root:root@mongo:27017/"
      ME_CONFIG_BASICAUTH: "false"
    depends_on:
      - mongo

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: app-mailhog
    ports:
      - "8025:8025"   # UI
      - "1025:1025"   # SMTP

volumes:
  dbdata:
  mongodata:
